version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poptin-app-prod
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ./.env:/var/www/html/.env
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    depends_on:
      - mysql
      - redis
      - reverb
    networks:
      - poptin-network-prod

  mysql:
    image: mysql:8.0
    container_name: poptin-mysql-prod
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: poll_management
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data_prod:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - poptin-network-prod

  redis:
    image: redis:7-alpine
    container_name: poptin-redis-prod
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_prod:/data
    networks:
      - poptin-network-prod

  reverb:
    image: laravel/reverb:latest
    container_name: poptin-reverb-prod
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - REVERB_APP_ID=${REVERB_APP_ID}
      - REVERB_APP_KEY=${REVERB_APP_KEY}
      - REVERB_APP_SECRET=${REVERB_APP_SECRET}
      - REVERB_HOST=0.0.0.0
      - REVERB_PORT=8080
      - REVERB_SCHEME=https
      - REVERB_DEBUG=false
    networks:
      - poptin-network-prod

volumes:
  mysql_data_prod:
    driver: local
  redis_data_prod:
    driver: local

networks:
  poptin-network-prod:
    driver: bridge
